# -*- coding: utf-8 -*-
{
    'name': 'Teacher Attendance',
    'version': '1.0',
    'category': 'Human Resources',
    'summary': 'Manage teacher attendance with QR codes, geolocation, and schedules.',
    'author': 'Odoo',
    'website': 'https://www.odoo.com',
    'depends': ['base', 'web', 'mail'],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'report/attendance_report_templates.xml',
        'views/academic_views.xml',
        'views/classroom_views.xml',
        'views/attendance_log_views.xml',
        'views/menu_views.xml',
        'views/attendance_dashboard_views.xml',
        'views/res_users_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'teacher_attendance/static/src/components/history/history.js',
            'teacher_attendance/static/src/components/history/history.xml',
            'teacher_attendance/static/src/components/scanner/scanner.js',
            'teacher_attendance/static/src/components/scanner/scanner.xml',
            'teacher_attendance/static/src/components/scanner/scanner.scss',
            'teacher_attendance/static/src/widgets/location_picker/location_picker.js',
            'teacher_attendance/static/src/widgets/location_picker/location_picker.xml',
            'teacher_attendance/static/src/components/signature/signature.js',
            'teacher_attendance/static/src/components/signature/signature.xml',
            'teacher_attendance/static/src/components/occupancy_map/occupancy_map.js',
            'teacher_attendance/static/src/components/occupancy_map/occupancy_map.xml',
            'teacher_attendance/static/src/components/kiosk/kiosk.js',
            'teacher_attendance/static/src/components/kiosk/kiosk.xml',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
